name: markdownhorse

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  formatcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: "yarn"
      - run: yarn install
      - run: yarn formatcheck
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: "yarn"
      - run: yarn install
      - run: yarn lint
  buildcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: "yarn"
      - run: yarn install
      - run: yarn build
      - run: if [[ $(git status --short) ]]; then echo "Performing a production build generated different files than what was committed. Please re-run \"yarn build\" and commit the changes."; fi
